@rootURL = http://localhost:5175

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/books/
accept: application/json

###
GET {{rootURL}}/api/books/1
accept: application/json

###
POST {{rootURL}}/api/books
Content-Type: application/json
{
  "id": 6,
  "title": "Bible",
  "author": "Mankind",
  "yearPublished": 1
}
###
PUT {{rootURL}}/api/books/5
Content-Type: application/json
{
  "id": 5,
  "title": "Bible",
  "author": "Mankind",
  "yearPublished": 1
}
###
DELETE {{rootURL}}/api/books/2
